### ISSUE TITLE
the link not work

### ISSUE THREAD

**Issue by lion10** [gazaskygeeks/code-academy#8]
the section that talks about the Function, point 5 the link not work (arrow function)

**Comment by HusseinAoda2** [comment]
Excuse me
You can provide me with the link
حسين عودة 
https://husseinaoda.wordpress.com/
-- 
ارسلت بشكل آمن مع Tutanota. احصل على صندوق بريد مشفر وخالي من الإعلانات:
https://tutanota.com



27 مارس 2020 19:57 بواسطة notifications@github.com:

**Comment by MohammedYehia** [comment]
Fixed 
thanks
